name: nix_build_overlay

on:

  push:
    branches: [ master ]
    commit-ignore:
    - [automatic update]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CACHIX_AUTH_TOKEN: ${{secrets.CACHIX}}
  PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}

jobs:

  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.PUSH_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: cachix/cachix-action@v15
        with:
          name: ctu-mrs
          authToken: '${{ secrets.CACHIX }}'
          extraPullNames: ros

      - run: |
          git clone https://github.com/ctu-mrs/buildfarm2 /tmp/buildfarm2
          /tmp/buildfarm2/scripts/clone_nixed_packages.sh mrs unstable
          /tmp/buildfarm2/scripts/clone_nixed_packages.sh thirdparty unstable
          /tmp/buildfarm2/scripts/clone_nixed_packages.sh nonbloom unstable
          /tmp/buildfarm2/scripts/extract_deps_json.py /tmp/workspace ./deps.json

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "ctu-mrs@github.com"
          git add .
          git commit -m "automatic update" || echo "nothing to commit"

      - run: nix build .#all --refresh --accept-flake-config --impure
      - run: nix run nixpkgs#cachix -- push ctu-mrs ./result

      - run: |
          git push
